package raven.modal.demo.model.enuns;

public enum EnumStatusAgendamento {
    AGENDADO, AGUARDANDO, CHAMADO, REAGENDAR, ATENDIDO, CANCELADOPELOPACIENTE, VEIOEDESISTIU,
    CANCELADOPELACLINICA, TRANSFERIDO, ENCAIXE, CANCELADOPELOCONSULTORIO, PARTICULAR;
}
