package raven.modal.demo.model.enuns;

public enum EnumTipoAtendimento {
    CONSULTA, MONITORIZACAO, ROTINAGINECOLOGICA, ROTINARETORNO, TTO,
    TTO1VEZ, TTORETORNO, PRENATAL, PRENATALCOMUN, PRENATALRETORNO, ROTINAPOSPARTO, EXAME, COLETA,
    TRANSFERENCIA, PARTICULAR, ROTINA, TELECONSULTA, SEMREGISTRO, FERTILIDADE;
}
