package raven.modal.demo.model.enuns;

public enum LAYOUT_IMG {
    LAYOUT_1_GRANDE,
    LAYOUT_1_MEDIA,
    LAYOUT_2_GRANDE,
    LAYOUT_2_MEDIA,
    LAYOUT_3_MEDIA,
    LAYOUT_4_GRANDE,
    LAYOUT_4_MEDIA,
    LAYOUT_4_PEQUENA,
    LAYOUT_6_MEDIA,
    LAYOUT_6_GRANDE,
    LAYOUT_8_PEQUENA,
    LAYOUT_8_GRANDE,
    LAYOUT_9_PEQUENA,
    LAYOUT_12_PEQUENA,
    LAYOUT_15_PEQUENA,
    LAYOUT_LAUDO_E_4_IMG,
    LAYOUT_LAUDO_E_5_IMG,
    LAYOUT_LAUDO_DESCRICAO_IMG;
}